### PR TITLE
fixes: Lint, Filter logic and Styles

### PR DESCRIPTION
**Pull request by aashutoshrathi**
💄 lint: Fix lint config and errors
🚀 feat: useEffect to filter and styling fixes

### CODE REVIEW

**Comment by mohitkyadav** [comment]
@aashutoshrathi why everything failing?

**Comment by aashutoshrathi** [comment]
Gomen'nasai.
Checking

**Comment by aashutoshrathi** [comment]
image

**Comment by aashutoshrathi** [comment]
@mohitkyadav Netlify broke some things, fixed.

**Comment by mohitkyadav** [comment]
@aashutoshrathi functionality not working

**Comment by aashutoshrathi** [comment]
That's weird, it works on local.

image


@mohitkyadav can you check in yours?

**Comment by mohitkyadav** [comment]
@aashutoshrathi it works on local for me as well 😄

**Comment by mohitkyadav** [comment]
image
see even in the react dev tools i can see colleges

**Comment by aashutoshrathi** [comment]
Fuck ```// eslint-disable-next-line react/no-array-index-key```

**Comment by aashutoshrathi** [comment]
@mohitkyadav review

**Review by mohitkyadav — APPROVED** [review]

**Pull request merged**
